goApp:
  replicaCount: 1
  resources:
    limits:
      cpu: "1"
      memory: 128Mi

postgresql:
  primary:
    persistence:
      size: 256Mi

redis:
  master:
    service:
      type: ClusterIP
      nodePorts:
        redis: ""

rabbitmq:
  service:
    type: ClusterIP
    nodePorts:
      amqp: ""
