// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/opentelemetry.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package postgres

import (
	"context"

	_sourceDomain "github.com/danicc097/todo-ddd-example/internal/modules/auth/domain"
	userDomain "github.com/danicc097/todo-ddd-example/internal/modules/user/domain"
	"go.opentelemetry.io/otel/attribute"

	"go.opentelemetry.io/otel"
	_codes "go.opentelemetry.io/otel/codes"

	semconv "go.opentelemetry.io/otel/semconv/v1.37.0"
	"go.opentelemetry.io/otel/trace"
)

// AuthRepositoryWithTracing implements AuthRepository interface instrumented with open telemetry spans
type AuthRepositoryWithTracing struct {
	_sourceDomain.AuthRepository
	_instance      string
	_spanDecorator func(span trace.Span, params, results map[string]interface{})
}

// NewAuthRepositoryWithTracing returns AuthRepositoryWithTracing
func NewAuthRepositoryWithTracing(base _sourceDomain.AuthRepository, instance string, spanDecorator ...func(span trace.Span, params, results map[string]interface{})) AuthRepositoryWithTracing {
	d := AuthRepositoryWithTracing{
		AuthRepository: base,
		_instance:      instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// FindByUserID implements AuthRepository
func (_d AuthRepositoryWithTracing) FindByUserID(ctx context.Context, userID userDomain.UserID) (up1 *_sourceDomain.UserAuth, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "AuthRepository.FindByUserID", trace.WithAttributes(
		semconv.DBSystemNamePostgreSQL,
		semconv.PeerServiceKey.String("postgres"),
		attribute.String("db.operation", "FindByUserID"),
	))
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":    ctx,
				"userID": userID}, map[string]interface{}{
				"up1": up1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.AuthRepository.FindByUserID(ctx, userID)
}

// Save implements AuthRepository
func (_d AuthRepositoryWithTracing) Save(ctx context.Context, auth *_sourceDomain.UserAuth) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "AuthRepository.Save", trace.WithAttributes(
		semconv.DBSystemNamePostgreSQL,
		semconv.PeerServiceKey.String("postgres"),
		attribute.String("db.operation", "Save"),
	))
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"auth": auth}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.AuthRepository.Save(ctx, auth)
}
