/**
 * Automatically generated by @grafana/openapi-to-k6: 0.4.1
 * Do not edit manually.
 * Todo DDD API
 * A Todo api with delusions of grandeur.
 * Service version: 1.0.0
 */
import { URL, URLSearchParams } from "https://jslib.k6.io/url/1.0.0/index.js";

import http from "k6/http";
import type { Params, Response } from "k6/http";

export interface IdResponse {
  id: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
  messages: string[];
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: string[];
  msg: string;
  detail: ValidationErrorDetail;
  ctx?: ValidationErrorCtx;
}

/**
 * Details of the error
 */
export interface ValidationErrorDetail {
  /** The actual value that failed validation */
  value: string;
}

export type WorkspaceRole = string;

export interface OnboardWorkspaceRequest {
  /** The display name of the workspace. */
  name: string;
  /** A brief description of the workspace purpose. */
  description?: string;
  /** Initial extra members to add to the workspace. */
  members?: unknown;
}

export interface AddWorkspaceMemberRequest {
  userId: string;
  role: WorkspaceRole;
}

export interface Workspace {
  id: string;
  name: string;
  description: string;
}

export interface AssignTagToTodoRequest {
  tagId: string;
}

export interface Todo {
  id: string;
  workspaceId: string;
  title: string;
  status: TodoStatus;
  createdAt: string;
  /** @nullable */
  dueDate?: string | null;
  recurrenceInterval?: RecurrenceInterval;
  /** @nullable */
  recurrenceAmount?: number | null;
  completionLogs?: CompletionLog[];
  focusSessions?: FocusSession[];
}

export interface CompletionLog {
  timestamp: string;
  actorId: string;
}

export interface FocusSession {
  id: string;
  startTime: string;
  /** @nullable */
  endTime?: string | null;
}

export interface CreateTodoRequest {
  title: string;
  /** @nullable */
  dueDate?: string | null;
  recurrenceInterval?: RecurrenceInterval;
  /**
   * @minimum 1
   * @nullable
   */
  recurrenceAmount?: number | null;
}

export interface CreateTagRequest {
  name: string;
}

export interface CommitTaskRequest {
  todoId: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  cost: number;
  date: string;
}

export type TodoStatus = (typeof TodoStatus)[keyof typeof TodoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TodoStatus = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  ARCHIVED: "ARCHIVED",
} as const;

/**
 * @nullable
 */
export type RecurrenceInterval =
  | (typeof RecurrenceInterval)[keyof typeof RecurrenceInterval]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecurrenceInterval = {
  DAILY: "DAILY",
  WEEKLY: "WEEKLY",
  MONTHLY: "MONTHLY",
} as const;

export interface LoginRequestBody {
  email: string;
  password: string;
}

export interface LoginResponseBody {
  accessToken: string;
}

export interface InitiateTOTPResponseBody {
  provisioningUri: string;
}

export interface VerifyTOTPRequestBody {
  code: string;
}

export interface RegisterUserRequestBody {
  email: string;
  name: string;
  /**
   * @minLength 12
   * @maxLength 128
   */
  password: string;
}

export interface User {
  id: string;
  email: string;
  name: string;
}

export interface Tag {
  id: string;
  name: string;
}

export type ErrorResponseResponseError = {
  code?: string;
  message?: string;
  trace_id?: string;
  validation?: HTTPValidationError;
};

export type ErrorResponseResponse = {
  error?: ErrorResponseResponseError;
};

/**
 * Maximum number of records to return.
 */
export type LimitParameter = number;

/**
 * Number of records to skip.
 */
export type OffsetParameter = number;

/**
 * Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response.

 */
export type IdempotencyKeyParameter = string;

export type RegisterHeaders = {
  /**
 * Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response.

 */
  "Idempotency-Key"?: IdempotencyKeyParameter;
};

export type GetWorkspaceTodosParams = {
  /**
   * Maximum number of records to return.
   * @minimum 1
   * @maximum 100
   */
  limit?: LimitParameter;
  /**
   * Number of records to skip.
   * @minimum 0
   */
  offset?: OffsetParameter;
};

export type CreateTodoHeaders = {
  /**
 * Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response.

 */
  "Idempotency-Key"?: IdempotencyKeyParameter;
};

export type CompleteTodoHeaders = {
  /**
 * Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response.

 */
  "Idempotency-Key"?: IdempotencyKeyParameter;
};

export type AssignTagToTodoHeaders = {
  /**
 * Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response.

 */
  "Idempotency-Key"?: IdempotencyKeyParameter;
};

export type GetUserWorkspacesParams = {
  /**
   * Maximum number of records to return.
   * @minimum 1
   * @maximum 100
   */
  limit?: LimitParameter;
  /**
   * Number of records to skip.
   * @minimum 0
   */
  offset?: OffsetParameter;
};

export type ListWorkspacesParams = {
  /**
   * Maximum number of records to return.
   * @minimum 1
   * @maximum 100
   */
  limit?: LimitParameter;
  /**
   * Number of records to skip.
   * @minimum 0
   */
  offset?: OffsetParameter;
};

export type OnboardWorkspaceHeaders = {
  /**
 * Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response.

 */
  "Idempotency-Key"?: IdempotencyKeyParameter;
};

export type AddWorkspaceMemberHeaders = {
  /**
 * Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response.

 */
  "Idempotency-Key"?: IdempotencyKeyParameter;
};

export type CreateTagHeaders = {
  /**
 * Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response.

 */
  "Idempotency-Key"?: IdempotencyKeyParameter;
};

/**
 * This is the base client to use for interacting with the API.
 */
export class TodoDDDAPIClient {
  private cleanBaseUrl: string;
  private commonRequestParameters: Params;

  constructor(clientOptions: {
    baseUrl: string;
    commonRequestParameters?: Params;
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "");

    this.commonRequestParameters = clientOptions.commonRequestParameters || {};
  }

  /**
   * @summary Health check
   */
  ping(requestParameters?: Params): {
    response: Response;
    data: string;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/ping`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "ping",
    };
  }

  /**
   * @summary Register a new user with password
   */
  register(
    registerUserRequestBody: RegisterUserRequestBody,
    headers?: RegisterHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: IdResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/auth/register`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(registerUserRequestBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "register",
    };
  }

  /**
   * @summary Login with email and password
   */
  login(
    loginRequestBody: LoginRequestBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: LoginResponseBody;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/auth/login`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(loginRequestBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "login",
    };
  }

  /**
   * @summary Initiate TOTP setup for the user
   */
  initiateTOTP(requestParameters?: Params): {
    response: Response;
    data: InitiateTOTPResponseBody;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/auth/totp/initiate`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "initiateTOTP",
    };
  }

  /**
   * @summary Verify and activate TOTP
   */
  verifyTOTP(
    verifyTOTPRequestBody: VerifyTOTPRequestBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: LoginResponseBody;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/auth/totp/verify`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(verifyTOTPRequestBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "verifyTOTP",
    };
  }

  /**
   * @summary List all todos for a workspace
   */
  getWorkspaceTodos(
    id: string,
    params?: GetWorkspaceTodosParams,
    requestParameters?: Params,
  ): {
    response: Response;
    data: Todo[];
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/workspaces/${id}/todos` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "getWorkspaceTodos",
    };
  }

  /**
   * @summary Create a new todo
   */
  createTodo(
    id: string,
    createTodoRequest: CreateTodoRequest,
    headers?: CreateTodoHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: IdResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/workspaces/${id}/todos`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(createTodoRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "createTodo",
    };
  }

  /**
   * @summary Get a todo by ID
   */
  getTodoByID(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: Todo;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/todos/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "getTodoByID",
    };
  }

  /**
   * @summary Complete a todo
   */
  completeTodo(
    id: string,
    headers?: CompleteTodoHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/todos/${id}/complete`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("PATCH", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "completeTodo",
    };
  }

  /**
   * @summary Assign a tag to a todo
   */
  assignTagToTodo(
    id: string,
    assignTagToTodoRequest: AssignTagToTodoRequest,
    headers?: AssignTagToTodoHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/todos/${id}/tags`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(assignTagToTodoRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "assignTagToTodo",
    };
  }

  /**
   * @summary Start focus session
   */
  startFocus(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/todos/${id}/focus/start`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "startFocus",
    };
  }

  /**
   * @summary Stop focus session
   */
  stopFocus(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/todos/${id}/focus/stop`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "stopFocus",
    };
  }

  /**
   * @summary Commit a task to daily schedule
   */
  commitTask(
    commitTaskRequest: CommitTaskRequest,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/schedule/commit`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(commitTaskRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "commitTask",
    };
  }

  getUserByID(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: User;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/users/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "getUserByID",
    };
  }

  /**
   * @summary Get all workspaces for a user
   */
  getUserWorkspaces(
    id: string,
    params?: GetUserWorkspacesParams,
    requestParameters?: Params,
  ): {
    response: Response;
    data: Workspace[];
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/users/${id}/workspaces` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "getUserWorkspaces",
    };
  }

  /**
   * @summary List all workspaces
   */
  listWorkspaces(
    params?: ListWorkspacesParams,
    requestParameters?: Params,
  ): {
    response: Response;
    data: Workspace[];
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/workspaces` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "listWorkspaces",
    };
  }

  /**
   * @summary Onboard a new workspace with initial members
   */
  onboardWorkspace(
    onboardWorkspaceRequest: OnboardWorkspaceRequest,
    headers?: OnboardWorkspaceHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: IdResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/workspaces`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(onboardWorkspaceRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "onboardWorkspace",
    };
  }

  /**
   * @summary Delete a workspace
   */
  deleteWorkspace(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/workspaces/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "DELETE",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "deleteWorkspace",
    };
  }

  /**
   * @summary Add a member to a workspace
   */
  addWorkspaceMember(
    id: string,
    addWorkspaceMemberRequest: AddWorkspaceMemberRequest,
    headers?: AddWorkspaceMemberHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/workspaces/${id}/members`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(addWorkspaceMemberRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "addWorkspaceMember",
    };
  }

  /**
   * @summary Remove a member from a workspace
   */
  removeWorkspaceMember(
    id: string,
    userId: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl + `/workspaces/${id}/members/${userId}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "DELETE",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "removeWorkspaceMember",
    };
  }

  /**
   * @summary Get all tags for a workspace
   */
  getWorkspaceTags(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: Tag[];
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/workspaces/${id}/tags`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "getWorkspaceTags",
    };
  }

  /**
   * @summary Create a new tag
   */
  createTag(
    id: string,
    createTagRequest: CreateTagRequest,
    headers?: CreateTagHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: IdResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/workspaces/${id}/tags`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(createTagRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "createTag",
    };
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params,
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    };
  }
}
