// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/cache.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorator

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/danicc097/todo-ddd-example/internal/infrastructure/cache"
	_sourceDomain "github.com/danicc097/todo-ddd-example/internal/modules/workspace/domain"
	"github.com/google/uuid"
	"github.com/redis/go-redis/v9"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

type WorkspaceRepositoryWithCache struct {
	base   _sourceDomain.WorkspaceRepository
	client *redis.Client
	ttl    time.Duration
	codec  cache.Codec[*_sourceDomain.Workspace]
}

func NewWorkspaceRepositoryWithCache(
	base _sourceDomain.WorkspaceRepository,
	client *redis.Client,
	ttl time.Duration,
	codec cache.Codec[*_sourceDomain.Workspace],
) WorkspaceRepositoryWithCache {
	return WorkspaceRepositoryWithCache{
		base:   base,
		client: client,
		ttl:    ttl,
		codec:  codec,
	}
}

func (d WorkspaceRepositoryWithCache) key(id string) string {
	return fmt.Sprintf("ws:%s", id)
}

func (d WorkspaceRepositoryWithCache) Delete(ctx context.Context, id uuid.UUID) (err error) {
	return d.base.Delete(ctx, id)
}

func (d WorkspaceRepositoryWithCache) FindAll(ctx context.Context) (wpa1 []*_sourceDomain.Workspace, err error) {
	return d.base.FindAll(ctx)
}

func (d WorkspaceRepositoryWithCache) FindByID(ctx context.Context, id uuid.UUID) (wp1 *_sourceDomain.Workspace, err error) {

	var cacheVal []byte
	var unmarshalErr error

	span := trace.SpanFromContext(ctx)
	key := d.key(fmt.Sprintf("%v", id))

	span.SetAttributes(attribute.String("cache.key", key))

	cacheVal, err = d.client.Get(ctx, key).Bytes()
	if err == nil {
		wp1, unmarshalErr = d.codec.Unmarshal(cacheVal)
		if unmarshalErr == nil {
			span.SetAttributes(attribute.Bool("cache.hit", true))
			slog.DebugContext(ctx, "cache hit", slog.String("key", key))
			return wp1, nil
		}
		slog.WarnContext(ctx, "cache hit but unmarshal failed", slog.String("key", key), slog.String("error", unmarshalErr.Error()))
	}

	span.SetAttributes(attribute.Bool("cache.hit", false))
	slog.DebugContext(ctx, "cache miss", slog.String("key", key))

	wp1, err = d.base.FindByID(ctx, id)
	if err != nil {
		return wp1, err
	}

	if data, marshalErr := d.codec.Marshal(wp1); marshalErr == nil {
		d.client.Set(ctx, key, data, d.ttl)
	}

	return wp1, nil
}

func (d WorkspaceRepositoryWithCache) Save(ctx context.Context, w *_sourceDomain.Workspace) (err error) {

	err = d.base.Save(ctx, w)
	if err != nil {
		return err
	}

	entity := w
	key := d.key(entity.ID().String())
	d.client.Del(ctx, key)

	slog.DebugContext(ctx, "cache invalidated", slog.String("key", key))

	return nil
}
