// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/opentelemetry.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package postgres

import (
	"context"

	_sourceDomain "github.com/danicc097/todo-ddd-example/internal/modules/todo/domain"
	"github.com/google/uuid"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	_codes "go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

// TagRepositoryWithTracing implements TagRepository interface instrumented with open telemetry spans
type TagRepositoryWithTracing struct {
	_sourceDomain.TagRepository
	_instance      string
	_spanDecorator func(span trace.Span, params, results map[string]interface{})
}

// NewTagRepositoryWithTracing returns TagRepositoryWithTracing
func NewTagRepositoryWithTracing(base _sourceDomain.TagRepository, instance string, spanDecorator ...func(span trace.Span, params, results map[string]interface{})) TagRepositoryWithTracing {
	d := TagRepositoryWithTracing{
		TagRepository: base,
		_instance:     instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// FindByID implements TagRepository
func (_d TagRepositoryWithTracing) FindByID(ctx context.Context, id uuid.UUID) (tp1 *_sourceDomain.Tag, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "TagRepository.FindByID")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"id":  id}, map[string]interface{}{
				"tp1": tp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.TagRepository.FindByID(ctx, id)
}

// FindByName implements TagRepository
func (_d TagRepositoryWithTracing) FindByName(ctx context.Context, name string) (tp1 *_sourceDomain.Tag, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "TagRepository.FindByName")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"name": name}, map[string]interface{}{
				"tp1": tp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.TagRepository.FindByName(ctx, name)
}

// Save implements TagRepository
func (_d TagRepositoryWithTracing) Save(ctx context.Context, tag *_sourceDomain.Tag) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "TagRepository.Save")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"tag": tag}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.TagRepository.Save(ctx, tag)
}
