// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/opentelemetry.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package postgres

import (
	"context"

	_sourceApplication "github.com/danicc097/todo-ddd-example/internal/modules/todo/application"
	"github.com/danicc097/todo-ddd-example/internal/modules/todo/domain"
	wsDomain "github.com/danicc097/todo-ddd-example/internal/modules/workspace/domain"
	"go.opentelemetry.io/otel/attribute"

	"go.opentelemetry.io/otel"
	_codes "go.opentelemetry.io/otel/codes"

	semconv "go.opentelemetry.io/otel/semconv/v1.37.0"
	"go.opentelemetry.io/otel/trace"
)

// TodoQueryServiceWithTracing implements TodoQueryService interface instrumented with open telemetry spans
type TodoQueryServiceWithTracing struct {
	_sourceApplication.TodoQueryService
	_instance      string
	_spanDecorator func(span trace.Span, params, results map[string]interface{})
}

// NewTodoQueryServiceWithTracing returns TodoQueryServiceWithTracing
func NewTodoQueryServiceWithTracing(base _sourceApplication.TodoQueryService, instance string, spanDecorator ...func(span trace.Span, params, results map[string]interface{})) TodoQueryServiceWithTracing {
	d := TodoQueryServiceWithTracing{
		TodoQueryService: base,
		_instance:        instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// GetAllByWorkspace implements TodoQueryService
func (_d TodoQueryServiceWithTracing) GetAllByWorkspace(ctx context.Context, wsID wsDomain.WorkspaceID, limit int32, offset int32) (ta1 []_sourceApplication.TodoReadModel, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "TodoQueryService.GetAllByWorkspace", trace.WithAttributes(
		semconv.DBSystemNamePostgreSQL,
		semconv.PeerServiceKey.String("postgres"),
		attribute.String("db.operation", "GetAllByWorkspace"),
	))
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":    ctx,
				"wsID":   wsID,
				"limit":  limit,
				"offset": offset}, map[string]interface{}{
				"ta1": ta1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.TodoQueryService.GetAllByWorkspace(ctx, wsID, limit, offset)
}

// GetByID implements TodoQueryService
func (_d TodoQueryServiceWithTracing) GetByID(ctx context.Context, id domain.TodoID) (tp1 *_sourceApplication.TodoReadModel, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "TodoQueryService.GetByID", trace.WithAttributes(
		semconv.DBSystemNamePostgreSQL,
		semconv.PeerServiceKey.String("postgres"),
		attribute.String("db.operation", "GetByID"),
	))
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"id":  id}, map[string]interface{}{
				"tp1": tp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.TodoQueryService.GetByID(ctx, id)
}
