// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/opentelemetry.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package postgres

import (
	"context"

	_sourceDomain "github.com/danicc097/todo-ddd-example/internal/modules/todo/domain"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	_codes "go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

// TodoRepositoryWithTracing implements TodoRepository interface instrumented with open telemetry spans
type TodoRepositoryWithTracing struct {
	_sourceDomain.TodoRepository
	_instance      string
	_spanDecorator func(span trace.Span, params, results map[string]interface{})
}

// NewTodoRepositoryWithTracing returns TodoRepositoryWithTracing
func NewTodoRepositoryWithTracing(base _sourceDomain.TodoRepository, instance string, spanDecorator ...func(span trace.Span, params, results map[string]interface{})) TodoRepositoryWithTracing {
	d := TodoRepositoryWithTracing{
		TodoRepository: base,
		_instance:      instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// FindAll implements TodoRepository
func (_d TodoRepositoryWithTracing) FindAll(ctx context.Context) (tpa1 []*_sourceDomain.Todo, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "TodoRepository.FindAll")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx}, map[string]interface{}{
				"tpa1": tpa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.TodoRepository.FindAll(ctx)
}

// FindByID implements TodoRepository
func (_d TodoRepositoryWithTracing) FindByID(ctx context.Context, id _sourceDomain.TodoID) (tp1 *_sourceDomain.Todo, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "TodoRepository.FindByID")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"id":  id}, map[string]interface{}{
				"tp1": tp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.TodoRepository.FindByID(ctx, id)
}

// Save implements TodoRepository
func (_d TodoRepositoryWithTracing) Save(ctx context.Context, todo *_sourceDomain.Todo) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "TodoRepository.Save")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"todo": todo}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.TodoRepository.Save(ctx, todo)
}

// Update implements TodoRepository
func (_d TodoRepositoryWithTracing) Update(ctx context.Context, todo *_sourceDomain.Todo) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "TodoRepository.Update")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"todo": todo}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.TodoRepository.Update(ctx, todo)
}
