# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
services:
  db:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 256M

  redis:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  rabbitmq:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  caddy:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  otel-collector:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  jaeger:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  prometheus:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
