{{- if .Values.goApp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: go-app-secret
  labels:
    app.kubernetes.io/name: go-app
    {{- include "todo-ddd-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  MFA_MASTER_KEY: {{ .Values.goApp.secrets.mfaMasterKey | quote }}
  DB_PASS: {{ .Values.goApp.secrets.dbPass | quote }}
  RABBITMQ_URL: {{ .Values.goApp.secrets.rabbitmqUrl | quote }}
{{- end }}
