{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    app.kubernetes.io/name: rabbitmq
    {{- include "todo-ddd-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.auth.username | quote }}
  password: {{ .Values.rabbitmq.auth.password | quote }}
{{- end }}
