// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/transactional.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorator

import (
	"context"

	_sourceApplication "github.com/danicc097/todo-ddd-example/internal/modules/todo/application"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	infraDB "github.com/danicc097/todo-ddd-example/internal/infrastructure/db"
)

// CompleteTodoUseCaseWithTransaction implements CompleteTodoUseCase with transaction boundaries
type CompleteTodoUseCaseWithTransaction struct {
	base _sourceApplication.CompleteTodoUseCase
	pool *pgxpool.Pool
}

// NewCompleteTodoUseCaseWithTransaction returns CompleteTodoUseCaseWithTransaction
func NewCompleteTodoUseCaseWithTransaction(base _sourceApplication.CompleteTodoUseCase, pool *pgxpool.Pool) CompleteTodoUseCaseWithTransaction {
	return CompleteTodoUseCaseWithTransaction{
		base: base,
		pool: pool,
	}
}

func (d CompleteTodoUseCaseWithTransaction) Execute(ctx context.Context, id uuid.UUID) (err error) {
	// Case: returns (error) - T is inferred as 'any'
	_, txErr := infraDB.RunInTx(ctx, d.pool, func(ctx context.Context) (any, error) {
		return nil, d.base.Execute(ctx, id)
	})
	return txErr
}
