// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/transactional.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorator

import (
	"context"

	_sourceApplication "github.com/danicc097/todo-ddd-example/internal/modules/todo/application"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	infraDB "github.com/danicc097/todo-ddd-example/internal/infrastructure/db"
)

// CreateTagUseCaseWithTransaction implements CreateTagUseCase with transaction boundaries
type CreateTagUseCaseWithTransaction struct {
	base _sourceApplication.CreateTagUseCase
	pool *pgxpool.Pool
}

// NewCreateTagUseCaseWithTransaction returns CreateTagUseCaseWithTransaction
func NewCreateTagUseCaseWithTransaction(base _sourceApplication.CreateTagUseCase, pool *pgxpool.Pool) CreateTagUseCaseWithTransaction {
	return CreateTagUseCaseWithTransaction{
		base: base,
		pool: pool,
	}
}

func (d CreateTagUseCaseWithTransaction) Execute(ctx context.Context, name string) (u1 uuid.UUID, err error) {
	// Case: returns (Value, error) - T is inferred as the first return type
	return infraDB.RunInTx(ctx, d.pool, func(ctx context.Context) (u1 uuid.UUID, err error) {
		return d.base.Execute(ctx, name)
	})
}
