// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/transactional.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorator

import (
	"context"

	_sourceApplication "github.com/danicc097/todo-ddd-example/internal/modules/todo/application"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	infraDB "github.com/danicc097/todo-ddd-example/internal/infrastructure/db"
)

// CreateTodoUseCaseWithTransaction implements CreateTodoUseCase with transaction boundaries
type CreateTodoUseCaseWithTransaction struct {
	base _sourceApplication.CreateTodoUseCase
	pool *pgxpool.Pool
}

// NewCreateTodoUseCaseWithTransaction returns CreateTodoUseCaseWithTransaction
func NewCreateTodoUseCaseWithTransaction(base _sourceApplication.CreateTodoUseCase, pool *pgxpool.Pool) CreateTodoUseCaseWithTransaction {
	return CreateTodoUseCaseWithTransaction{
		base: base,
		pool: pool,
	}
}

func (d CreateTodoUseCaseWithTransaction) Execute(ctx context.Context, cmd _sourceApplication.CreateTodoCommand) (u1 uuid.UUID, err error) {
	// Case: returns (Value, error) - T is inferred as the first return type
	return infraDB.RunInTx(ctx, d.pool, func(ctx context.Context) (u1 uuid.UUID, err error) {
		return d.base.Execute(ctx, cmd)
	})
}
