// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/cache.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorator

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/danicc097/todo-ddd-example/internal/infrastructure/cache"
	_sourceDomain "github.com/danicc097/todo-ddd-example/internal/modules/todo/domain"
	"github.com/google/uuid"
	"github.com/redis/go-redis/v9"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

type TagRepositoryWithCache struct {
	base   _sourceDomain.TagRepository
	client *redis.Client
	ttl    time.Duration
	codec  cache.Codec[*_sourceDomain.Tag]
}

func NewTagRepositoryWithCache(
	base _sourceDomain.TagRepository,
	client *redis.Client,
	ttl time.Duration,
	codec cache.Codec[*_sourceDomain.Tag],
) TagRepositoryWithCache {
	return TagRepositoryWithCache{
		base:   base,
		client: client,
		ttl:    ttl,
		codec:  codec,
	}
}

func (d TagRepositoryWithCache) key(id string) string {
	return fmt.Sprintf("tag:%s", id)
}

func (d TagRepositoryWithCache) FindByID(ctx context.Context, id uuid.UUID) (tp1 *_sourceDomain.Tag, err error) {

	var cacheVal []byte
	var unmarshalErr error

	span := trace.SpanFromContext(ctx)
	key := d.key(fmt.Sprintf("%v", id))

	span.SetAttributes(attribute.String("cache.key", key))

	cacheVal, err = d.client.Get(ctx, key).Bytes()
	if err == nil {
		tp1, unmarshalErr = d.codec.Unmarshal(cacheVal)
		if unmarshalErr == nil {
			span.SetAttributes(attribute.Bool("cache.hit", true))
			slog.DebugContext(ctx, "cache hit", slog.String("key", key))
			return tp1, nil
		}
		slog.WarnContext(ctx, "cache hit but unmarshal failed", slog.String("key", key), slog.String("error", unmarshalErr.Error()))
	}

	span.SetAttributes(attribute.Bool("cache.hit", false))
	slog.DebugContext(ctx, "cache miss", slog.String("key", key))

	tp1, err = d.base.FindByID(ctx, id)
	if err != nil {
		return tp1, err
	}

	if data, marshalErr := d.codec.Marshal(tp1); marshalErr == nil {
		d.client.Set(ctx, key, data, d.ttl)
	}

	return tp1, nil
}

func (d TagRepositoryWithCache) FindByName(ctx context.Context, name string) (tp1 *_sourceDomain.Tag, err error) {
	return d.base.FindByName(ctx, name)
}

func (d TagRepositoryWithCache) Save(ctx context.Context, tag *_sourceDomain.Tag) (err error) {

	err = d.base.Save(ctx, tag)
	if err != nil {
		return err
	}

	entity := tag
	key := d.key(entity.ID().String())
	d.client.Del(ctx, key)

	slog.DebugContext(ctx, "cache invalidated", slog.String("key", key))

	return nil
}
