// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/cache.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorator

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"time"

	api "github.com/danicc097/todo-ddd-example/internal/generated/api"
	"github.com/danicc097/todo-ddd-example/internal/infrastructure/cache"
	_sourceApplication "github.com/danicc097/todo-ddd-example/internal/modules/todo/application"
	"github.com/danicc097/todo-ddd-example/internal/modules/todo/domain"
	wsDomain "github.com/danicc097/todo-ddd-example/internal/modules/workspace/domain"
	"github.com/redis/go-redis/v9"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

type TodoQueryServiceWithCache struct {
	base   _sourceApplication.TodoQueryService
	client *redis.Client
	ttl    time.Duration
	codec  cache.Codec[*api.Todo]
}

func NewTodoQueryServiceWithCache(
	base _sourceApplication.TodoQueryService,
	client *redis.Client,
	ttl time.Duration,
	codec cache.Codec[*api.Todo],
) TodoQueryServiceWithCache {
	return TodoQueryServiceWithCache{
		base:   base,
		client: client,
		ttl:    ttl,
		codec:  codec,
	}
}

func (d TodoQueryServiceWithCache) key(id string) string {
	return fmt.Sprintf("todo_query:%s", id)
}

func (d TodoQueryServiceWithCache) collectionKey(method string, id string) string {
	return fmt.Sprintf("todo_query:collection:%s:%s", method, id)
}

func (d TodoQueryServiceWithCache) GetAllByWorkspace(ctx context.Context, wsID wsDomain.WorkspaceID) (ta1 []api.Todo, err error) {

	var cacheVal []byte

	span := trace.SpanFromContext(ctx)
	key := d.collectionKey("GetAllByWorkspace", fmt.Sprintf("%v", wsID))

	span.SetAttributes(attribute.String("cache.key", key))

	cacheVal, err = d.client.Get(ctx, key).Bytes()
	if err == nil {
		err = json.Unmarshal(cacheVal, &ta1)
		if err == nil {
			span.SetAttributes(attribute.Bool("cache.hit", true))
			slog.DebugContext(ctx, "cache hit", slog.String("key", key))
			return ta1, nil
		}
	}

	span.SetAttributes(attribute.Bool("cache.hit", false))
	slog.DebugContext(ctx, "cache miss", slog.String("key", key))

	ta1, err = d.base.GetAllByWorkspace(ctx, wsID)
	if err != nil {
		return ta1, err
	}

	if data, marshalErr := json.Marshal(ta1); marshalErr == nil {
		d.client.Set(ctx, key, data, d.ttl)
	}

	return ta1, nil
}

func (d TodoQueryServiceWithCache) GetByID(ctx context.Context, id domain.TodoID) (tp1 *api.Todo, err error) {

	var cacheVal []byte
	var unmarshalErr error

	span := trace.SpanFromContext(ctx)
	key := d.key(fmt.Sprintf("%v", id))

	span.SetAttributes(attribute.String("cache.key", key))

	cacheVal, err = d.client.Get(ctx, key).Bytes()
	if err == nil {
		tp1, unmarshalErr = d.codec.Unmarshal(cacheVal)
		if unmarshalErr == nil {
			span.SetAttributes(attribute.Bool("cache.hit", true))
			slog.DebugContext(ctx, "cache hit", slog.String("key", key))
			return tp1, nil
		}
		slog.WarnContext(ctx, "cache hit but unmarshal failed", slog.String("key", key), slog.String("error", unmarshalErr.Error()))
	}

	span.SetAttributes(attribute.Bool("cache.hit", false))
	slog.DebugContext(ctx, "cache miss", slog.String("key", key))

	tp1, err = d.base.GetByID(ctx, id)
	if err != nil {
		return tp1, err
	}

	if data, marshalErr := d.codec.Marshal(tp1); marshalErr == nil {
		d.client.Set(ctx, key, data, d.ttl)
	}

	return tp1, nil
}

func (d TodoQueryServiceWithCache) GetLastUpdateByWorkspace(ctx context.Context, wsID wsDomain.WorkspaceID) (tp1 *time.Time, err error) {
	return d.base.GetLastUpdateByWorkspace(ctx, wsID)
}
