// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/cache.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorator

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/danicc097/todo-ddd-example/internal/infrastructure/cache"
	_sourceDomain "github.com/danicc097/todo-ddd-example/internal/modules/todo/domain"
	wsDomain "github.com/danicc097/todo-ddd-example/internal/modules/workspace/domain"
	"github.com/redis/go-redis/v9"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

type TodoRepositoryWithCache struct {
	base   _sourceDomain.TodoRepository
	client *redis.Client
	ttl    time.Duration
	codec  cache.Codec[*_sourceDomain.Todo]
}

func NewTodoRepositoryWithCache(
	base _sourceDomain.TodoRepository,
	client *redis.Client,
	ttl time.Duration,
	codec cache.Codec[*_sourceDomain.Todo],
) TodoRepositoryWithCache {
	return TodoRepositoryWithCache{
		base:   base,
		client: client,
		ttl:    ttl,
		codec:  codec,
	}
}

func (d TodoRepositoryWithCache) key(id string) string {
	return fmt.Sprintf("todo_query:%s", id)
}

func (d TodoRepositoryWithCache) FindAllByWorkspace(ctx context.Context, wsID wsDomain.WorkspaceID) (tpa1 []*_sourceDomain.Todo, err error) {
	return d.base.FindAllByWorkspace(ctx, wsID)
}

func (d TodoRepositoryWithCache) FindByID(ctx context.Context, id _sourceDomain.TodoID) (tp1 *_sourceDomain.Todo, err error) {

	var cacheVal []byte
	var unmarshalErr error

	span := trace.SpanFromContext(ctx)
	key := d.key(fmt.Sprintf("%v", id))

	span.SetAttributes(attribute.String("cache.key", key))

	cacheVal, err = d.client.Get(ctx, key).Bytes()
	if err == nil {
		tp1, unmarshalErr = d.codec.Unmarshal(cacheVal)
		if unmarshalErr == nil {
			span.SetAttributes(attribute.Bool("cache.hit", true))
			slog.DebugContext(ctx, "cache hit", slog.String("key", key))
			return tp1, nil
		}
		slog.WarnContext(ctx, "cache hit but unmarshal failed", slog.String("key", key), slog.String("error", unmarshalErr.Error()))
	}

	span.SetAttributes(attribute.Bool("cache.hit", false))
	slog.DebugContext(ctx, "cache miss", slog.String("key", key))

	tp1, err = d.base.FindByID(ctx, id)
	if err != nil {
		return tp1, err
	}

	if data, marshalErr := d.codec.Marshal(tp1); marshalErr == nil {
		d.client.Set(ctx, key, data, d.ttl)
	}

	return tp1, nil
}

func (d TodoRepositoryWithCache) Save(ctx context.Context, todo *_sourceDomain.Todo) (err error) {

	err = d.base.Save(ctx, todo)
	if err != nil {
		return err
	}

	entity := todo
	key := d.key(entity.ID().String())
	d.client.Del(ctx, key)

	slog.DebugContext(ctx, "cache invalidated", slog.String("key", key))

	return nil
}

func (d TodoRepositoryWithCache) Update(ctx context.Context, todo *_sourceDomain.Todo) (err error) {

	err = d.base.Update(ctx, todo)
	if err != nil {
		return err
	}

	entity := todo
	key := d.key(entity.ID().String())
	d.client.Del(ctx, key)

	slog.DebugContext(ctx, "cache invalidated", slog.String("key", key))

	return nil
}
