// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/opentelemetry.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package postgres

import (
	"context"

	api "github.com/danicc097/todo-ddd-example/internal/generated/api"
	userDomain "github.com/danicc097/todo-ddd-example/internal/modules/user/domain"
	_sourceApplication "github.com/danicc097/todo-ddd-example/internal/modules/workspace/application"
	"github.com/danicc097/todo-ddd-example/internal/modules/workspace/domain"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	_codes "go.opentelemetry.io/otel/codes"

	semconv "go.opentelemetry.io/otel/semconv/v1.37.0"
	"go.opentelemetry.io/otel/trace"
)

// WorkspaceQueryServiceWithTracing implements WorkspaceQueryService interface instrumented with open telemetry spans
type WorkspaceQueryServiceWithTracing struct {
	_sourceApplication.WorkspaceQueryService
	_instance      string
	_spanDecorator func(span trace.Span, params, results map[string]interface{})
}

// NewWorkspaceQueryServiceWithTracing returns WorkspaceQueryServiceWithTracing
func NewWorkspaceQueryServiceWithTracing(base _sourceApplication.WorkspaceQueryService, instance string, spanDecorator ...func(span trace.Span, params, results map[string]interface{})) WorkspaceQueryServiceWithTracing {
	d := WorkspaceQueryServiceWithTracing{
		WorkspaceQueryService: base,
		_instance:             instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// List implements WorkspaceQueryService
func (_d WorkspaceQueryServiceWithTracing) List(ctx context.Context) (wa1 []api.Workspace, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WorkspaceQueryService.List", trace.WithAttributes(
		semconv.DBSystemNamePostgreSQL,
		semconv.PeerServiceKey.String("postgres"),
	))
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx}, map[string]interface{}{
				"wa1": wa1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WorkspaceQueryService.List(ctx)
}

// ListByUserID implements WorkspaceQueryService
func (_d WorkspaceQueryServiceWithTracing) ListByUserID(ctx context.Context, userID userDomain.UserID) (wa1 []api.Workspace, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WorkspaceQueryService.ListByUserID", trace.WithAttributes(
		semconv.DBSystemNamePostgreSQL,
		semconv.PeerServiceKey.String("postgres"),
	))
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":    ctx,
				"userID": userID}, map[string]interface{}{
				"wa1": wa1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WorkspaceQueryService.ListByUserID(ctx, userID)
}

// ListTagsByWorkspaceID implements WorkspaceQueryService
func (_d WorkspaceQueryServiceWithTracing) ListTagsByWorkspaceID(ctx context.Context, workspaceID domain.WorkspaceID) (ta1 []api.Tag, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WorkspaceQueryService.ListTagsByWorkspaceID", trace.WithAttributes(
		semconv.DBSystemNamePostgreSQL,
		semconv.PeerServiceKey.String("postgres"),
	))
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":         ctx,
				"workspaceID": workspaceID}, map[string]interface{}{
				"ta1": ta1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WorkspaceQueryService.ListTagsByWorkspaceID(ctx, workspaceID)
}
