// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/opentelemetry.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package postgres

import (
	"context"

	_sourceDomain "github.com/danicc097/todo-ddd-example/internal/modules/workspace/domain"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	_codes "go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

// WorkspaceRepositoryWithTracing implements WorkspaceRepository interface instrumented with open telemetry spans
type WorkspaceRepositoryWithTracing struct {
	_sourceDomain.WorkspaceRepository
	_instance      string
	_spanDecorator func(span trace.Span, params, results map[string]interface{})
}

// NewWorkspaceRepositoryWithTracing returns WorkspaceRepositoryWithTracing
func NewWorkspaceRepositoryWithTracing(base _sourceDomain.WorkspaceRepository, instance string, spanDecorator ...func(span trace.Span, params, results map[string]interface{})) WorkspaceRepositoryWithTracing {
	d := WorkspaceRepositoryWithTracing{
		WorkspaceRepository: base,
		_instance:           instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// Delete implements WorkspaceRepository
func (_d WorkspaceRepositoryWithTracing) Delete(ctx context.Context, id _sourceDomain.WorkspaceID) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WorkspaceRepository.Delete")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"id":  id}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WorkspaceRepository.Delete(ctx, id)
}

// FindAll implements WorkspaceRepository
func (_d WorkspaceRepositoryWithTracing) FindAll(ctx context.Context) (wpa1 []*_sourceDomain.Workspace, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WorkspaceRepository.FindAll")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx}, map[string]interface{}{
				"wpa1": wpa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WorkspaceRepository.FindAll(ctx)
}

// FindByID implements WorkspaceRepository
func (_d WorkspaceRepositoryWithTracing) FindByID(ctx context.Context, id _sourceDomain.WorkspaceID) (wp1 *_sourceDomain.Workspace, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WorkspaceRepository.FindByID")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"id":  id}, map[string]interface{}{
				"wp1": wp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WorkspaceRepository.FindByID(ctx, id)
}

// Save implements WorkspaceRepository
func (_d WorkspaceRepositoryWithTracing) Save(ctx context.Context, w *_sourceDomain.Workspace) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WorkspaceRepository.Save")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"w":   w}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WorkspaceRepository.Save(ctx, w)
}
