// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/danicc097/todo-ddd-example/internal/shared/application"
)

type FakeRequestHandler[C any, R any] struct {
	HandleStub        func(context.Context, C) (R, error)
	handleMutex       sync.RWMutex
	handleArgsForCall []struct {
		arg1 context.Context
		arg2 C
	}
	handleReturns struct {
		result1 R
		result2 error
	}
	handleReturnsOnCall map[int]struct {
		result1 R
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRequestHandler[C, R]) Handle(arg1 context.Context, arg2 C) (R, error) {
	fake.handleMutex.Lock()
	ret, specificReturn := fake.handleReturnsOnCall[len(fake.handleArgsForCall)]
	fake.handleArgsForCall = append(fake.handleArgsForCall, struct {
		arg1 context.Context
		arg2 C
	}{arg1, arg2})
	stub := fake.HandleStub
	fakeReturns := fake.handleReturns
	fake.recordInvocation("Handle", []interface{}{arg1, arg2})
	fake.handleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRequestHandler[C, R]) HandleCallCount() int {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	return len(fake.handleArgsForCall)
}

func (fake *FakeRequestHandler[C, R]) HandleCalls(stub func(context.Context, C) (R, error)) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = stub
}

func (fake *FakeRequestHandler[C, R]) HandleArgsForCall(i int) (context.Context, C) {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	argsForCall := fake.handleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRequestHandler[C, R]) HandleReturns(result1 R, result2 error) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = nil
	fake.handleReturns = struct {
		result1 R
		result2 error
	}{result1, result2}
}

func (fake *FakeRequestHandler[C, R]) HandleReturnsOnCall(i int, result1 R, result2 error) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = nil
	if fake.handleReturnsOnCall == nil {
		fake.handleReturnsOnCall = make(map[int]struct {
			result1 R
			result2 error
		})
	}
	fake.handleReturnsOnCall[i] = struct {
		result1 R
		result2 error
	}{result1, result2}
}

func (fake *FakeRequestHandler[C, R]) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRequestHandler[C, R]) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ application.RequestHandler[any, any] = new(FakeRequestHandler[any, any])
