// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/opentelemetry.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package postgres

import (
	"context"

	_sourceDomain "github.com/danicc097/todo-ddd-example/internal/modules/user/domain"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	_codes "go.opentelemetry.io/otel/codes"

	semconv "go.opentelemetry.io/otel/semconv/v1.37.0"
	"go.opentelemetry.io/otel/trace"
)

// UserRepositoryWithTracing implements UserRepository interface instrumented with open telemetry spans
type UserRepositoryWithTracing struct {
	_sourceDomain.UserRepository
	_instance      string
	_spanDecorator func(span trace.Span, params, results map[string]interface{})
}

// NewUserRepositoryWithTracing returns UserRepositoryWithTracing
func NewUserRepositoryWithTracing(base _sourceDomain.UserRepository, instance string, spanDecorator ...func(span trace.Span, params, results map[string]interface{})) UserRepositoryWithTracing {
	d := UserRepositoryWithTracing{
		UserRepository: base,
		_instance:      instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// FindByEmail implements UserRepository
func (_d UserRepositoryWithTracing) FindByEmail(ctx context.Context, email _sourceDomain.UserEmail) (up1 *_sourceDomain.User, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "UserRepository.FindByEmail", trace.WithAttributes(
		semconv.DBSystemNamePostgreSQL,
		semconv.PeerServiceKey.String("postgres"),
	))
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":   ctx,
				"email": email}, map[string]interface{}{
				"up1": up1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.UserRepository.FindByEmail(ctx, email)
}

// FindByID implements UserRepository
func (_d UserRepositoryWithTracing) FindByID(ctx context.Context, id _sourceDomain.UserID) (up1 *_sourceDomain.User, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "UserRepository.FindByID", trace.WithAttributes(
		semconv.DBSystemNamePostgreSQL,
		semconv.PeerServiceKey.String("postgres"),
	))
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"id":  id}, map[string]interface{}{
				"up1": up1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.UserRepository.FindByID(ctx, id)
}

// Save implements UserRepository
func (_d UserRepositoryWithTracing) Save(ctx context.Context, user *_sourceDomain.User) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "UserRepository.Save", trace.WithAttributes(
		semconv.DBSystemNamePostgreSQL,
		semconv.PeerServiceKey.String("postgres"),
	))
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"user": user}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.UserRepository.Save(ctx, user)
}
