// Code generated by counterfeiter. DO NOT EDIT.
package domainfakes

import (
	"context"
	"sync"

	"github.com/danicc097/todo-ddd-example/internal/modules/todo/domain"
	domaina "github.com/danicc097/todo-ddd-example/internal/modules/workspace/domain"
)

type FakeTodoRepository struct {
	FindAllByWorkspaceStub        func(context.Context, domaina.WorkspaceID) ([]*domain.Todo, error)
	findAllByWorkspaceMutex       sync.RWMutex
	findAllByWorkspaceArgsForCall []struct {
		arg1 context.Context
		arg2 domaina.WorkspaceID
	}
	findAllByWorkspaceReturns struct {
		result1 []*domain.Todo
		result2 error
	}
	findAllByWorkspaceReturnsOnCall map[int]struct {
		result1 []*domain.Todo
		result2 error
	}
	FindByIDStub        func(context.Context, domain.TodoID) (*domain.Todo, error)
	findByIDMutex       sync.RWMutex
	findByIDArgsForCall []struct {
		arg1 context.Context
		arg2 domain.TodoID
	}
	findByIDReturns struct {
		result1 *domain.Todo
		result2 error
	}
	findByIDReturnsOnCall map[int]struct {
		result1 *domain.Todo
		result2 error
	}
	SaveStub        func(context.Context, *domain.Todo) error
	saveMutex       sync.RWMutex
	saveArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Todo
	}
	saveReturns struct {
		result1 error
	}
	saveReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateStub        func(context.Context, *domain.Todo) error
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Todo
	}
	updateReturns struct {
		result1 error
	}
	updateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTodoRepository) FindAllByWorkspace(arg1 context.Context, arg2 domaina.WorkspaceID) ([]*domain.Todo, error) {
	fake.findAllByWorkspaceMutex.Lock()
	ret, specificReturn := fake.findAllByWorkspaceReturnsOnCall[len(fake.findAllByWorkspaceArgsForCall)]
	fake.findAllByWorkspaceArgsForCall = append(fake.findAllByWorkspaceArgsForCall, struct {
		arg1 context.Context
		arg2 domaina.WorkspaceID
	}{arg1, arg2})
	stub := fake.FindAllByWorkspaceStub
	fakeReturns := fake.findAllByWorkspaceReturns
	fake.recordInvocation("FindAllByWorkspace", []interface{}{arg1, arg2})
	fake.findAllByWorkspaceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTodoRepository) FindAllByWorkspaceCallCount() int {
	fake.findAllByWorkspaceMutex.RLock()
	defer fake.findAllByWorkspaceMutex.RUnlock()
	return len(fake.findAllByWorkspaceArgsForCall)
}

func (fake *FakeTodoRepository) FindAllByWorkspaceCalls(stub func(context.Context, domaina.WorkspaceID) ([]*domain.Todo, error)) {
	fake.findAllByWorkspaceMutex.Lock()
	defer fake.findAllByWorkspaceMutex.Unlock()
	fake.FindAllByWorkspaceStub = stub
}

func (fake *FakeTodoRepository) FindAllByWorkspaceArgsForCall(i int) (context.Context, domaina.WorkspaceID) {
	fake.findAllByWorkspaceMutex.RLock()
	defer fake.findAllByWorkspaceMutex.RUnlock()
	argsForCall := fake.findAllByWorkspaceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTodoRepository) FindAllByWorkspaceReturns(result1 []*domain.Todo, result2 error) {
	fake.findAllByWorkspaceMutex.Lock()
	defer fake.findAllByWorkspaceMutex.Unlock()
	fake.FindAllByWorkspaceStub = nil
	fake.findAllByWorkspaceReturns = struct {
		result1 []*domain.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeTodoRepository) FindAllByWorkspaceReturnsOnCall(i int, result1 []*domain.Todo, result2 error) {
	fake.findAllByWorkspaceMutex.Lock()
	defer fake.findAllByWorkspaceMutex.Unlock()
	fake.FindAllByWorkspaceStub = nil
	if fake.findAllByWorkspaceReturnsOnCall == nil {
		fake.findAllByWorkspaceReturnsOnCall = make(map[int]struct {
			result1 []*domain.Todo
			result2 error
		})
	}
	fake.findAllByWorkspaceReturnsOnCall[i] = struct {
		result1 []*domain.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeTodoRepository) FindByID(arg1 context.Context, arg2 domain.TodoID) (*domain.Todo, error) {
	fake.findByIDMutex.Lock()
	ret, specificReturn := fake.findByIDReturnsOnCall[len(fake.findByIDArgsForCall)]
	fake.findByIDArgsForCall = append(fake.findByIDArgsForCall, struct {
		arg1 context.Context
		arg2 domain.TodoID
	}{arg1, arg2})
	stub := fake.FindByIDStub
	fakeReturns := fake.findByIDReturns
	fake.recordInvocation("FindByID", []interface{}{arg1, arg2})
	fake.findByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTodoRepository) FindByIDCallCount() int {
	fake.findByIDMutex.RLock()
	defer fake.findByIDMutex.RUnlock()
	return len(fake.findByIDArgsForCall)
}

func (fake *FakeTodoRepository) FindByIDCalls(stub func(context.Context, domain.TodoID) (*domain.Todo, error)) {
	fake.findByIDMutex.Lock()
	defer fake.findByIDMutex.Unlock()
	fake.FindByIDStub = stub
}

func (fake *FakeTodoRepository) FindByIDArgsForCall(i int) (context.Context, domain.TodoID) {
	fake.findByIDMutex.RLock()
	defer fake.findByIDMutex.RUnlock()
	argsForCall := fake.findByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTodoRepository) FindByIDReturns(result1 *domain.Todo, result2 error) {
	fake.findByIDMutex.Lock()
	defer fake.findByIDMutex.Unlock()
	fake.FindByIDStub = nil
	fake.findByIDReturns = struct {
		result1 *domain.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeTodoRepository) FindByIDReturnsOnCall(i int, result1 *domain.Todo, result2 error) {
	fake.findByIDMutex.Lock()
	defer fake.findByIDMutex.Unlock()
	fake.FindByIDStub = nil
	if fake.findByIDReturnsOnCall == nil {
		fake.findByIDReturnsOnCall = make(map[int]struct {
			result1 *domain.Todo
			result2 error
		})
	}
	fake.findByIDReturnsOnCall[i] = struct {
		result1 *domain.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeTodoRepository) Save(arg1 context.Context, arg2 *domain.Todo) error {
	fake.saveMutex.Lock()
	ret, specificReturn := fake.saveReturnsOnCall[len(fake.saveArgsForCall)]
	fake.saveArgsForCall = append(fake.saveArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Todo
	}{arg1, arg2})
	stub := fake.SaveStub
	fakeReturns := fake.saveReturns
	fake.recordInvocation("Save", []interface{}{arg1, arg2})
	fake.saveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTodoRepository) SaveCallCount() int {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	return len(fake.saveArgsForCall)
}

func (fake *FakeTodoRepository) SaveCalls(stub func(context.Context, *domain.Todo) error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = stub
}

func (fake *FakeTodoRepository) SaveArgsForCall(i int) (context.Context, *domain.Todo) {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	argsForCall := fake.saveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTodoRepository) SaveReturns(result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	fake.saveReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTodoRepository) SaveReturnsOnCall(i int, result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	if fake.saveReturnsOnCall == nil {
		fake.saveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTodoRepository) Update(arg1 context.Context, arg2 *domain.Todo) error {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Todo
	}{arg1, arg2})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1, arg2})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTodoRepository) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeTodoRepository) UpdateCalls(stub func(context.Context, *domain.Todo) error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *FakeTodoRepository) UpdateArgsForCall(i int) (context.Context, *domain.Todo) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTodoRepository) UpdateReturns(result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTodoRepository) UpdateReturnsOnCall(i int, result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTodoRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTodoRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.TodoRepository = new(FakeTodoRepository)
