// Code generated by counterfeiter. DO NOT EDIT.
package domainfakes

import (
	"context"
	"sync"

	"github.com/danicc097/todo-ddd-example/internal/modules/todo/domain"
	"github.com/google/uuid"
)

type FakeEventPublisher struct {
	PublishTagAddedStub        func(context.Context, uuid.UUID, uuid.UUID) error
	publishTagAddedMutex       sync.RWMutex
	publishTagAddedArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	publishTagAddedReturns struct {
		result1 error
	}
	publishTagAddedReturnsOnCall map[int]struct {
		result1 error
	}
	PublishTodoCreatedStub        func(context.Context, *domain.Todo) error
	publishTodoCreatedMutex       sync.RWMutex
	publishTodoCreatedArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Todo
	}
	publishTodoCreatedReturns struct {
		result1 error
	}
	publishTodoCreatedReturnsOnCall map[int]struct {
		result1 error
	}
	PublishTodoUpdatedStub        func(context.Context, *domain.Todo) error
	publishTodoUpdatedMutex       sync.RWMutex
	publishTodoUpdatedArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Todo
	}
	publishTodoUpdatedReturns struct {
		result1 error
	}
	publishTodoUpdatedReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEventPublisher) PublishTagAdded(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.publishTagAddedMutex.Lock()
	ret, specificReturn := fake.publishTagAddedReturnsOnCall[len(fake.publishTagAddedArgsForCall)]
	fake.publishTagAddedArgsForCall = append(fake.publishTagAddedArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.PublishTagAddedStub
	fakeReturns := fake.publishTagAddedReturns
	fake.recordInvocation("PublishTagAdded", []interface{}{arg1, arg2, arg3})
	fake.publishTagAddedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeEventPublisher) PublishTagAddedCallCount() int {
	fake.publishTagAddedMutex.RLock()
	defer fake.publishTagAddedMutex.RUnlock()
	return len(fake.publishTagAddedArgsForCall)
}

func (fake *FakeEventPublisher) PublishTagAddedCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.publishTagAddedMutex.Lock()
	defer fake.publishTagAddedMutex.Unlock()
	fake.PublishTagAddedStub = stub
}

func (fake *FakeEventPublisher) PublishTagAddedArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.publishTagAddedMutex.RLock()
	defer fake.publishTagAddedMutex.RUnlock()
	argsForCall := fake.publishTagAddedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeEventPublisher) PublishTagAddedReturns(result1 error) {
	fake.publishTagAddedMutex.Lock()
	defer fake.publishTagAddedMutex.Unlock()
	fake.PublishTagAddedStub = nil
	fake.publishTagAddedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeEventPublisher) PublishTagAddedReturnsOnCall(i int, result1 error) {
	fake.publishTagAddedMutex.Lock()
	defer fake.publishTagAddedMutex.Unlock()
	fake.PublishTagAddedStub = nil
	if fake.publishTagAddedReturnsOnCall == nil {
		fake.publishTagAddedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.publishTagAddedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeEventPublisher) PublishTodoCreated(arg1 context.Context, arg2 *domain.Todo) error {
	fake.publishTodoCreatedMutex.Lock()
	ret, specificReturn := fake.publishTodoCreatedReturnsOnCall[len(fake.publishTodoCreatedArgsForCall)]
	fake.publishTodoCreatedArgsForCall = append(fake.publishTodoCreatedArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Todo
	}{arg1, arg2})
	stub := fake.PublishTodoCreatedStub
	fakeReturns := fake.publishTodoCreatedReturns
	fake.recordInvocation("PublishTodoCreated", []interface{}{arg1, arg2})
	fake.publishTodoCreatedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeEventPublisher) PublishTodoCreatedCallCount() int {
	fake.publishTodoCreatedMutex.RLock()
	defer fake.publishTodoCreatedMutex.RUnlock()
	return len(fake.publishTodoCreatedArgsForCall)
}

func (fake *FakeEventPublisher) PublishTodoCreatedCalls(stub func(context.Context, *domain.Todo) error) {
	fake.publishTodoCreatedMutex.Lock()
	defer fake.publishTodoCreatedMutex.Unlock()
	fake.PublishTodoCreatedStub = stub
}

func (fake *FakeEventPublisher) PublishTodoCreatedArgsForCall(i int) (context.Context, *domain.Todo) {
	fake.publishTodoCreatedMutex.RLock()
	defer fake.publishTodoCreatedMutex.RUnlock()
	argsForCall := fake.publishTodoCreatedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeEventPublisher) PublishTodoCreatedReturns(result1 error) {
	fake.publishTodoCreatedMutex.Lock()
	defer fake.publishTodoCreatedMutex.Unlock()
	fake.PublishTodoCreatedStub = nil
	fake.publishTodoCreatedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeEventPublisher) PublishTodoCreatedReturnsOnCall(i int, result1 error) {
	fake.publishTodoCreatedMutex.Lock()
	defer fake.publishTodoCreatedMutex.Unlock()
	fake.PublishTodoCreatedStub = nil
	if fake.publishTodoCreatedReturnsOnCall == nil {
		fake.publishTodoCreatedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.publishTodoCreatedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeEventPublisher) PublishTodoUpdated(arg1 context.Context, arg2 *domain.Todo) error {
	fake.publishTodoUpdatedMutex.Lock()
	ret, specificReturn := fake.publishTodoUpdatedReturnsOnCall[len(fake.publishTodoUpdatedArgsForCall)]
	fake.publishTodoUpdatedArgsForCall = append(fake.publishTodoUpdatedArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Todo
	}{arg1, arg2})
	stub := fake.PublishTodoUpdatedStub
	fakeReturns := fake.publishTodoUpdatedReturns
	fake.recordInvocation("PublishTodoUpdated", []interface{}{arg1, arg2})
	fake.publishTodoUpdatedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeEventPublisher) PublishTodoUpdatedCallCount() int {
	fake.publishTodoUpdatedMutex.RLock()
	defer fake.publishTodoUpdatedMutex.RUnlock()
	return len(fake.publishTodoUpdatedArgsForCall)
}

func (fake *FakeEventPublisher) PublishTodoUpdatedCalls(stub func(context.Context, *domain.Todo) error) {
	fake.publishTodoUpdatedMutex.Lock()
	defer fake.publishTodoUpdatedMutex.Unlock()
	fake.PublishTodoUpdatedStub = stub
}

func (fake *FakeEventPublisher) PublishTodoUpdatedArgsForCall(i int) (context.Context, *domain.Todo) {
	fake.publishTodoUpdatedMutex.RLock()
	defer fake.publishTodoUpdatedMutex.RUnlock()
	argsForCall := fake.publishTodoUpdatedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeEventPublisher) PublishTodoUpdatedReturns(result1 error) {
	fake.publishTodoUpdatedMutex.Lock()
	defer fake.publishTodoUpdatedMutex.Unlock()
	fake.PublishTodoUpdatedStub = nil
	fake.publishTodoUpdatedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeEventPublisher) PublishTodoUpdatedReturnsOnCall(i int, result1 error) {
	fake.publishTodoUpdatedMutex.Lock()
	defer fake.publishTodoUpdatedMutex.Unlock()
	fake.PublishTodoUpdatedStub = nil
	if fake.publishTodoUpdatedReturnsOnCall == nil {
		fake.publishTodoUpdatedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.publishTodoUpdatedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeEventPublisher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeEventPublisher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.EventPublisher = new(FakeEventPublisher)
