// Code generated by counterfeiter. DO NOT EDIT.
package domainfakes

import (
	"context"
	"sync"

	"github.com/danicc097/todo-ddd-example/internal/modules/todo/domain"
)

type FakeEventPublisher struct {
	PublishTodoCreatedStub        func(context.Context, *domain.Todo) error
	publishTodoCreatedMutex       sync.RWMutex
	publishTodoCreatedArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Todo
	}
	publishTodoCreatedReturns struct {
		result1 error
	}
	publishTodoCreatedReturnsOnCall map[int]struct {
		result1 error
	}
	PublishTodoUpdatedStub        func(context.Context, *domain.Todo) error
	publishTodoUpdatedMutex       sync.RWMutex
	publishTodoUpdatedArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Todo
	}
	publishTodoUpdatedReturns struct {
		result1 error
	}
	publishTodoUpdatedReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEventPublisher) PublishTodoCreated(arg1 context.Context, arg2 *domain.Todo) error {
	fake.publishTodoCreatedMutex.Lock()
	ret, specificReturn := fake.publishTodoCreatedReturnsOnCall[len(fake.publishTodoCreatedArgsForCall)]
	fake.publishTodoCreatedArgsForCall = append(fake.publishTodoCreatedArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Todo
	}{arg1, arg2})
	stub := fake.PublishTodoCreatedStub
	fakeReturns := fake.publishTodoCreatedReturns
	fake.recordInvocation("PublishTodoCreated", []interface{}{arg1, arg2})
	fake.publishTodoCreatedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeEventPublisher) PublishTodoCreatedCallCount() int {
	fake.publishTodoCreatedMutex.RLock()
	defer fake.publishTodoCreatedMutex.RUnlock()
	return len(fake.publishTodoCreatedArgsForCall)
}

func (fake *FakeEventPublisher) PublishTodoCreatedArgsForCall(i int) (context.Context, *domain.Todo) {
	fake.publishTodoCreatedMutex.RLock()
	defer fake.publishTodoCreatedMutex.RUnlock()
	return fake.publishTodoCreatedArgsForCall[i].arg1, fake.publishTodoCreatedArgsForCall[i].arg2
}

func (fake *FakeEventPublisher) PublishTodoCreatedReturns(result1 error) {
	fake.publishTodoCreatedMutex.Lock()
	defer fake.publishTodoCreatedMutex.Unlock()
	fake.PublishTodoCreatedStub = nil
	fake.publishTodoCreatedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeEventPublisher) PublishTodoUpdated(arg1 context.Context, arg2 *domain.Todo) error {
	fake.publishTodoUpdatedMutex.Lock()
	ret, specificReturn := fake.publishTodoUpdatedReturnsOnCall[len(fake.publishTodoUpdatedArgsForCall)]
	fake.publishTodoUpdatedArgsForCall = append(fake.publishTodoUpdatedArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Todo
	}{arg1, arg2})
	stub := fake.PublishTodoUpdatedStub
	fakeReturns := fake.publishTodoUpdatedReturns
	fake.recordInvocation("PublishTodoUpdated", []interface{}{arg1, arg2})
	fake.publishTodoUpdatedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeEventPublisher) PublishTodoUpdatedCallCount() int {
	fake.publishTodoUpdatedMutex.RLock()
	defer fake.publishTodoUpdatedMutex.RUnlock()
	return len(fake.publishTodoUpdatedArgsForCall)
}

func (fake *FakeEventPublisher) PublishTodoUpdatedArgsForCall(i int) (context.Context, *domain.Todo) {
	fake.publishTodoUpdatedMutex.RLock()
	defer fake.publishTodoUpdatedMutex.RUnlock()
	return fake.publishTodoUpdatedArgsForCall[i].arg1, fake.publishTodoUpdatedArgsForCall[i].arg2
}

func (fake *FakeEventPublisher) PublishTodoUpdatedReturns(result1 error) {
	fake.publishTodoUpdatedMutex.Lock()
	defer fake.publishTodoUpdatedMutex.Unlock()
	fake.PublishTodoUpdatedStub = nil
	fake.publishTodoUpdatedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeEventPublisher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeEventPublisher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.EventPublisher = new(FakeEventPublisher)
