// Code generated by project. DO NOT EDIT.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/google/uuid"
	"github.com/spf13/cobra"

	"github.com/danicc097/todo-ddd-example/internal/generated/client"
	todoDomain "github.com/danicc097/todo-ddd-example/internal/modules/todo/domain"
	userDomain "github.com/danicc097/todo-ddd-example/internal/modules/user/domain"
	workspaceDomain "github.com/danicc097/todo-ddd-example/internal/modules/workspace/domain"
)

var _ = todoDomain.TodoID{}
var _ = userDomain.UserID{}
var _ = workspaceDomain.WorkspaceID{}

func RegisterGeneratedCommands(rootCmd *cobra.Command, getClient func() (*client.ClientWithResponses, context.Context)) {

	cmdLogin := &cobra.Command{
		Use:   "login",
		Short: "Login with email and password",

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			bodyStr, _ := cmd.Flags().GetString("payload")
			var reqBody client.LoginJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.LoginWithResponse(ctx, reqBody)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}
	cmdLogin.Flags().StringP("payload", "p", "", "JSON payload for the request body")

	rootCmd.AddCommand(cmdLogin)

	cmdRegister := &cobra.Command{
		Use:   "register",
		Short: "Register a new user with password",

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			params := &client.RegisterParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")
			var reqBody client.RegisterJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.RegisterWithResponse(ctx, params, reqBody)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}
	cmdRegister.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdRegister.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdRegister)

	cmdInitiateTOTP := &cobra.Command{
		Use:   "initiate-totp",
		Short: "Initiate TOTP setup for the user",

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			resp, err := c.InitiateTOTPWithResponse(ctx)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}

	rootCmd.AddCommand(cmdInitiateTOTP)

	cmdVerifyTOTP := &cobra.Command{
		Use:   "verify-totp",
		Short: "Verify and activate TOTP",

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			bodyStr, _ := cmd.Flags().GetString("payload")
			var reqBody client.VerifyTOTPJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.VerifyTOTPWithResponse(ctx, reqBody)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}
	cmdVerifyTOTP.Flags().StringP("payload", "p", "", "JSON payload for the request body")

	rootCmd.AddCommand(cmdVerifyTOTP)

	cmdGetAllTodos := &cobra.Command{
		Use:   "get-all-todos",
		Short: "List all todos",

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			resp, err := c.GetAllTodosWithResponse(ctx)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}

	rootCmd.AddCommand(cmdGetAllTodos)

	cmdCreateTodo := &cobra.Command{
		Use:   "create-todo",
		Short: "Create a new todo",

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			params := &client.CreateTodoParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")
			var reqBody client.CreateTodoJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.CreateTodoWithResponse(ctx, params, reqBody)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}
	cmdCreateTodo.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdCreateTodo.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdCreateTodo)

	cmdGetTodoByID := &cobra.Command{
		Use:   "get-todo-by-id [id]",
		Short: "Get a todo by ID",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			paramid := todoDomain.TodoID{UUID: uuid.MustParse(args[0])}

			resp, err := c.GetTodoByIDWithResponse(ctx, paramid)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}

	rootCmd.AddCommand(cmdGetTodoByID)

	cmdCompleteTodo := &cobra.Command{
		Use:   "complete-todo [id]",
		Short: "Complete a todo",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			paramid := todoDomain.TodoID{UUID: uuid.MustParse(args[0])}

			params := &client.CompleteTodoParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			resp, err := c.CompleteTodoWithResponse(ctx, paramid, params)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}
	cmdCompleteTodo.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdCompleteTodo)

	cmdAssignTagToTodo := &cobra.Command{
		Use:   "assign-tag-to-todo [id]",
		Short: "Assign a tag to a todo",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			paramid := todoDomain.TodoID{UUID: uuid.MustParse(args[0])}

			params := &client.AssignTagToTodoParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")
			var reqBody client.AssignTagToTodoJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.AssignTagToTodoWithResponse(ctx, paramid, params, reqBody)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}
	cmdAssignTagToTodo.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdAssignTagToTodo.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdAssignTagToTodo)

	cmdRegisterUser := &cobra.Command{
		Use:   "register-user",
		Short: "",

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			params := &client.RegisterUserParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")
			var reqBody client.RegisterUserJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.RegisterUserWithResponse(ctx, params, reqBody)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}
	cmdRegisterUser.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdRegisterUser.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdRegisterUser)

	cmdGetUserByID := &cobra.Command{
		Use:   "get-user-by-id [id]",
		Short: "",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			paramid := userDomain.UserID{UUID: uuid.MustParse(args[0])}

			resp, err := c.GetUserByIDWithResponse(ctx, paramid)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}

	rootCmd.AddCommand(cmdGetUserByID)

	cmdGetUserWorkspaces := &cobra.Command{
		Use:   "get-user-workspaces [id]",
		Short: "Get all workspaces for a user",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			paramid := userDomain.UserID{UUID: uuid.MustParse(args[0])}

			resp, err := c.GetUserWorkspacesWithResponse(ctx, paramid)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}

	rootCmd.AddCommand(cmdGetUserWorkspaces)

	cmdListWorkspaces := &cobra.Command{
		Use:   "list-workspaces",
		Short: "List all workspaces",

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			resp, err := c.ListWorkspacesWithResponse(ctx)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}

	rootCmd.AddCommand(cmdListWorkspaces)

	cmdOnboardWorkspace := &cobra.Command{
		Use:   "onboard-workspace",
		Short: "Onboard a new workspace with initial members",

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			params := &client.OnboardWorkspaceParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")
			var reqBody client.OnboardWorkspaceJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.OnboardWorkspaceWithResponse(ctx, params, reqBody)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}
	cmdOnboardWorkspace.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdOnboardWorkspace.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdOnboardWorkspace)

	cmdDeleteWorkspace := &cobra.Command{
		Use:   "delete-workspace [id]",
		Short: "Delete a workspace",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			paramid := workspaceDomain.WorkspaceID{UUID: uuid.MustParse(args[0])}

			resp, err := c.DeleteWorkspaceWithResponse(ctx, paramid)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}

	rootCmd.AddCommand(cmdDeleteWorkspace)

	cmdAddWorkspaceMember := &cobra.Command{
		Use:   "add-workspace-member [id]",
		Short: "Add a member to a workspace",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			paramid := workspaceDomain.WorkspaceID{UUID: uuid.MustParse(args[0])}

			params := &client.AddWorkspaceMemberParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")
			var reqBody client.AddWorkspaceMemberJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.AddWorkspaceMemberWithResponse(ctx, paramid, params, reqBody)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}
	cmdAddWorkspaceMember.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdAddWorkspaceMember.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdAddWorkspaceMember)

	cmdRemoveWorkspaceMember := &cobra.Command{
		Use:   "remove-workspace-member [id] [userId]",
		Short: "Remove a member from a workspace",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			paramid := workspaceDomain.WorkspaceID{UUID: uuid.MustParse(args[0])}

			paramuserId := userDomain.UserID{UUID: uuid.MustParse(args[1])}

			resp, err := c.RemoveWorkspaceMemberWithResponse(ctx, paramid, paramuserId)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}

	rootCmd.AddCommand(cmdRemoveWorkspaceMember)

	cmdGetWorkspaceTags := &cobra.Command{
		Use:   "get-workspace-tags [id]",
		Short: "Get all tags for a workspace",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			paramid := workspaceDomain.WorkspaceID{UUID: uuid.MustParse(args[0])}

			resp, err := c.GetWorkspaceTagsWithResponse(ctx, paramid)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}

	rootCmd.AddCommand(cmdGetWorkspaceTags)

	cmdCreateTag := &cobra.Command{
		Use:   "create-tag [id]",
		Short: "Create a new tag",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			paramid := workspaceDomain.WorkspaceID{UUID: uuid.MustParse(args[0])}

			params := &client.CreateTagParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")
			var reqBody client.CreateTagJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.CreateTagWithResponse(ctx, paramid, params, reqBody)
			if err != nil {
				return err
			}

			fmt.Printf("Status: %d\nResponse: %s\n", resp.StatusCode(), string(resp.Body))
			return nil
		},
	}
	cmdCreateTag.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdCreateTag.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdCreateTag)

}
