// Code generated by project. DO NOT EDIT.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/google/uuid"
	"github.com/spf13/cobra"

	"github.com/danicc097/todo-ddd-example/internal/generated/client"
	todoDomain "github.com/danicc097/todo-ddd-example/internal/modules/todo/domain"
	userDomain "github.com/danicc097/todo-ddd-example/internal/modules/user/domain"
	workspaceDomain "github.com/danicc097/todo-ddd-example/internal/modules/workspace/domain"
)

var _ = todoDomain.TodoID{}
var _ = userDomain.UserID{}
var _ = workspaceDomain.WorkspaceID{}

func RegisterGeneratedCommands(rootCmd *cobra.Command, getClient func() (*client.ClientWithResponses, context.Context)) {

	cmdLogin := &cobra.Command{
		Use:           "login",
		Short:         "Login with email and password",
		SilenceUsage:  true,
		SilenceErrors: true,

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing Login"))
			}

			bodyStr, _ := cmd.Flags().GetString("payload")

			if debug && bodyStr != "" {
				fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("DEBUG: Payload: %s", bodyStr)))
			}

			var reqBody client.LoginJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.LoginWithResponse(ctx, reqBody)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdLogin.Flags().StringP("payload", "p", "", "JSON payload for the request body")

	rootCmd.AddCommand(cmdLogin)

	cmdRegister := &cobra.Command{
		Use:           "register",
		Short:         "Register a new user with password",
		SilenceUsage:  true,
		SilenceErrors: true,

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing Register"))
			}

			params := &client.RegisterParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")

			if debug && bodyStr != "" {
				fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("DEBUG: Payload: %s", bodyStr)))
			}

			var reqBody client.RegisterJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.RegisterWithResponse(ctx, params, reqBody)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdRegister.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdRegister.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdRegister)

	cmdInitiateTOTP := &cobra.Command{
		Use:           "initiate-totp",
		Short:         "Initiate TOTP setup for the user",
		SilenceUsage:  true,
		SilenceErrors: true,

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing InitiateTOTP"))
			}

			resp, err := c.InitiateTOTPWithResponse(ctx)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}

	rootCmd.AddCommand(cmdInitiateTOTP)

	cmdVerifyTOTP := &cobra.Command{
		Use:           "verify-totp",
		Short:         "Verify and activate TOTP",
		SilenceUsage:  true,
		SilenceErrors: true,

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing VerifyTOTP"))
			}

			bodyStr, _ := cmd.Flags().GetString("payload")

			if debug && bodyStr != "" {
				fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("DEBUG: Payload: %s", bodyStr)))
			}

			var reqBody client.VerifyTOTPJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.VerifyTOTPWithResponse(ctx, reqBody)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdVerifyTOTP.Flags().StringP("payload", "p", "", "JSON payload for the request body")

	rootCmd.AddCommand(cmdVerifyTOTP)

	cmdPing := &cobra.Command{
		Use:           "ping",
		Short:         "Health check",
		SilenceUsage:  true,
		SilenceErrors: true,

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing Ping"))
			}

			resp, err := c.PingWithResponse(ctx)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}

	rootCmd.AddCommand(cmdPing)

	cmdCommitTask := &cobra.Command{
		Use:           "commit-task",
		Short:         "Commit a task to daily schedule",
		SilenceUsage:  true,
		SilenceErrors: true,

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing CommitTask"))
			}

			bodyStr, _ := cmd.Flags().GetString("payload")

			if debug && bodyStr != "" {
				fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("DEBUG: Payload: %s", bodyStr)))
			}

			var reqBody client.CommitTaskJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.CommitTaskWithResponse(ctx, reqBody)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdCommitTask.Flags().StringP("payload", "p", "", "JSON payload for the request body")

	rootCmd.AddCommand(cmdCommitTask)

	cmdGetTodoByID := &cobra.Command{
		Use:           "get-todo-by-id [id]",
		Short:         "Get a todo by ID",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing GetTodoByID"))
			}

			paramid := todoDomain.TodoID(uuid.MustParse(args[0]))

			resp, err := c.GetTodoByIDWithResponse(ctx, paramid)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}

	rootCmd.AddCommand(cmdGetTodoByID)

	cmdCompleteTodo := &cobra.Command{
		Use:           "complete-todo [id]",
		Short:         "Complete a todo",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing CompleteTodo"))
			}

			paramid := todoDomain.TodoID(uuid.MustParse(args[0]))

			params := &client.CompleteTodoParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			resp, err := c.CompleteTodoWithResponse(ctx, paramid, params)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdCompleteTodo.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdCompleteTodo)

	cmdStartFocus := &cobra.Command{
		Use:           "start-focus [id]",
		Short:         "Start focus session",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing StartFocus"))
			}

			paramid := todoDomain.TodoID(uuid.MustParse(args[0]))

			resp, err := c.StartFocusWithResponse(ctx, paramid)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}

	rootCmd.AddCommand(cmdStartFocus)

	cmdStopFocus := &cobra.Command{
		Use:           "stop-focus [id]",
		Short:         "Stop focus session",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing StopFocus"))
			}

			paramid := todoDomain.TodoID(uuid.MustParse(args[0]))

			resp, err := c.StopFocusWithResponse(ctx, paramid)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}

	rootCmd.AddCommand(cmdStopFocus)

	cmdAssignTagToTodo := &cobra.Command{
		Use:           "assign-tag-to-todo [id]",
		Short:         "Assign a tag to a todo",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing AssignTagToTodo"))
			}

			paramid := todoDomain.TodoID(uuid.MustParse(args[0]))

			params := &client.AssignTagToTodoParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")

			if debug && bodyStr != "" {
				fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("DEBUG: Payload: %s", bodyStr)))
			}

			var reqBody client.AssignTagToTodoJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.AssignTagToTodoWithResponse(ctx, paramid, params, reqBody)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdAssignTagToTodo.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdAssignTagToTodo.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdAssignTagToTodo)

	cmdGetUserByID := &cobra.Command{
		Use:           "get-user-by-id [id]",
		Short:         "",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing GetUserByID"))
			}

			paramid := userDomain.UserID(uuid.MustParse(args[0]))

			resp, err := c.GetUserByIDWithResponse(ctx, paramid)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}

	rootCmd.AddCommand(cmdGetUserByID)

	cmdGetUserWorkspaces := &cobra.Command{
		Use:           "get-user-workspaces [id]",
		Short:         "Get all workspaces for a user",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing GetUserWorkspaces"))
			}

			paramid := userDomain.UserID(uuid.MustParse(args[0]))

			params := &client.GetUserWorkspacesParams{}
			if val, _ := cmd.Flags().GetInt("limit"); val != 0 {
				params.Limit = &val
			}
			if val, _ := cmd.Flags().GetInt("offset"); val != 0 {
				params.Offset = &val
			}

			resp, err := c.GetUserWorkspacesWithResponse(ctx, paramid, params)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdGetUserWorkspaces.Flags().Int("limit", 0, "Maximum number of records to return.")
	cmdGetUserWorkspaces.Flags().Int("offset", 0, "Number of records to skip.")

	rootCmd.AddCommand(cmdGetUserWorkspaces)

	cmdListWorkspaces := &cobra.Command{
		Use:           "list-workspaces",
		Short:         "List all workspaces",
		SilenceUsage:  true,
		SilenceErrors: true,

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing ListWorkspaces"))
			}

			params := &client.ListWorkspacesParams{}
			if val, _ := cmd.Flags().GetInt("limit"); val != 0 {
				params.Limit = &val
			}
			if val, _ := cmd.Flags().GetInt("offset"); val != 0 {
				params.Offset = &val
			}

			resp, err := c.ListWorkspacesWithResponse(ctx, params)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdListWorkspaces.Flags().Int("limit", 0, "Maximum number of records to return.")
	cmdListWorkspaces.Flags().Int("offset", 0, "Number of records to skip.")

	rootCmd.AddCommand(cmdListWorkspaces)

	cmdOnboardWorkspace := &cobra.Command{
		Use:           "onboard-workspace",
		Short:         "Onboard a new workspace with initial members",
		SilenceUsage:  true,
		SilenceErrors: true,

		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing OnboardWorkspace"))
			}

			params := &client.OnboardWorkspaceParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")

			if debug && bodyStr != "" {
				fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("DEBUG: Payload: %s", bodyStr)))
			}

			var reqBody client.OnboardWorkspaceJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.OnboardWorkspaceWithResponse(ctx, params, reqBody)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdOnboardWorkspace.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdOnboardWorkspace.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdOnboardWorkspace)

	cmdDeleteWorkspace := &cobra.Command{
		Use:           "delete-workspace [id]",
		Short:         "Delete a workspace",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing DeleteWorkspace"))
			}

			paramid := workspaceDomain.WorkspaceID(uuid.MustParse(args[0]))

			resp, err := c.DeleteWorkspaceWithResponse(ctx, paramid)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}

	rootCmd.AddCommand(cmdDeleteWorkspace)

	cmdAddWorkspaceMember := &cobra.Command{
		Use:           "add-workspace-member [id]",
		Short:         "Add a member to a workspace",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing AddWorkspaceMember"))
			}

			paramid := workspaceDomain.WorkspaceID(uuid.MustParse(args[0]))

			params := &client.AddWorkspaceMemberParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")

			if debug && bodyStr != "" {
				fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("DEBUG: Payload: %s", bodyStr)))
			}

			var reqBody client.AddWorkspaceMemberJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.AddWorkspaceMemberWithResponse(ctx, paramid, params, reqBody)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdAddWorkspaceMember.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdAddWorkspaceMember.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdAddWorkspaceMember)

	cmdRemoveWorkspaceMember := &cobra.Command{
		Use:           "remove-workspace-member [id] [userId]",
		Short:         "Remove a member from a workspace",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing RemoveWorkspaceMember"))
			}

			paramid := workspaceDomain.WorkspaceID(uuid.MustParse(args[0]))

			paramuserId := userDomain.UserID(uuid.MustParse(args[1]))

			resp, err := c.RemoveWorkspaceMemberWithResponse(ctx, paramid, paramuserId)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}

	rootCmd.AddCommand(cmdRemoveWorkspaceMember)

	cmdGetWorkspaceTags := &cobra.Command{
		Use:           "get-workspace-tags [id]",
		Short:         "Get all tags for a workspace",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing GetWorkspaceTags"))
			}

			paramid := workspaceDomain.WorkspaceID(uuid.MustParse(args[0]))

			resp, err := c.GetWorkspaceTagsWithResponse(ctx, paramid)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}

	rootCmd.AddCommand(cmdGetWorkspaceTags)

	cmdCreateTag := &cobra.Command{
		Use:           "create-tag [id]",
		Short:         "Create a new tag",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing CreateTag"))
			}

			paramid := workspaceDomain.WorkspaceID(uuid.MustParse(args[0]))

			params := &client.CreateTagParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")

			if debug && bodyStr != "" {
				fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("DEBUG: Payload: %s", bodyStr)))
			}

			var reqBody client.CreateTagJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.CreateTagWithResponse(ctx, paramid, params, reqBody)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdCreateTag.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdCreateTag.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdCreateTag)

	cmdGetWorkspaceTodos := &cobra.Command{
		Use:           "get-workspace-todos [id]",
		Short:         "List all todos for a workspace",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing GetWorkspaceTodos"))
			}

			paramid := workspaceDomain.WorkspaceID(uuid.MustParse(args[0]))

			params := &client.GetWorkspaceTodosParams{}
			if val, _ := cmd.Flags().GetInt("limit"); val != 0 {
				params.Limit = &val
			}
			if val, _ := cmd.Flags().GetInt("offset"); val != 0 {
				params.Offset = &val
			}

			resp, err := c.GetWorkspaceTodosWithResponse(ctx, paramid, params)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdGetWorkspaceTodos.Flags().Int("limit", 0, "Maximum number of records to return.")
	cmdGetWorkspaceTodos.Flags().Int("offset", 0, "Number of records to skip.")

	rootCmd.AddCommand(cmdGetWorkspaceTodos)

	cmdCreateTodo := &cobra.Command{
		Use:           "create-todo [id]",
		Short:         "Create a new todo",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, ctx := getClient()

			if debug {
				fmt.Fprintln(os.Stderr, styleHeader.Render("--> Executing CreateTodo"))
			}

			paramid := workspaceDomain.WorkspaceID(uuid.MustParse(args[0]))

			params := &client.CreateTodoParams{}
			if val, _ := cmd.Flags().GetString("idempotency-key"); val != "" {
				u := uuid.MustParse(val)
				params.IdempotencyKey = &u
			}

			bodyStr, _ := cmd.Flags().GetString("payload")

			if debug && bodyStr != "" {
				fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("DEBUG: Payload: %s", bodyStr)))
			}

			var reqBody client.CreateTodoJSONRequestBody
			if bodyStr != "" {
				if err := json.Unmarshal([]byte(bodyStr), &reqBody); err != nil {
					return fmt.Errorf("invalid json payload: %w", err)
				}
			}

			resp, err := c.CreateTodoWithResponse(ctx, paramid, params, reqBody)
			if err != nil {
				return err
			}

			if resp.StatusCode() >= 400 {
				fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			} else {
				fmt.Fprintln(os.Stderr, styleSuccess.Render(fmt.Sprintf("Status: %d", resp.StatusCode())))
			}

			if verbose {
				for k, v := range resp.HTTPResponse.Header {
					fmt.Fprintln(os.Stderr, styleDebug.Render(fmt.Sprintf("%s: %s", k, strings.Join(v, ", "))))
				}
			}

			if len(resp.Body) > 0 {
				fmt.Printf("%s\n", string(resp.Body))
			}

			if resp.StatusCode() >= 400 {
				return fmt.Errorf("request failed with status %d", resp.StatusCode())
			}

			return nil
		},
	}
	cmdCreateTodo.Flags().StringP("payload", "p", "", "JSON payload for the request body")
	cmdCreateTodo.Flags().String("idempotency-key", "", "Unique key to allow safe retries of non-idempotent requests. If a request with the same key is received, the server returns the cached response. ")

	rootCmd.AddCommand(cmdCreateTodo)

}
